; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const ABSORB
	const ACCELEROCK
	const ACID
	const ACID_ARMOR
	const ACID_SPRAY
	const ACROBATICS
	const ACUPRESSURE
	const AERIAL_ACE
	const AEROBLAST
	const AGILITY
	const AIR_CUTTER
	const AIR_SLASH
	const ALLY_SWITCH
	const AMNESIA
	const ANCIENTPOWER
	const AQUA_JET
	const AQUA_TAIL
	const ARM_THRUST
	const AROMATICMIST
	const ASSIST
	const ASSURANCE
	const ASTONISH
	const ATTRACT
	const AURA_SPHERE
	const AURORA_BEAM
	const AURORA_VEIL
	const AUTOTOMIZE
	const AVALANCHE
	const BABYDOLLEYES
	const BADDY_BAD
	const BARB_BARRAGE
	const BARRAGE
	const BARRIER
	const BATON_PASS
	const BEAT_UP
	const BELCH
	const BELLY_DRUM
	const BIDE
	const BIND
	const BITE
	const BLAST_BURN
	const BLAZE_KICK
	const BLIZZARD
	const BLOCK
	const BODY_PRESS
	const BODY_SLAM
	const BOLT_STRIKE
	const BONE_CLUB
	const BONE_RUSH
	const BONEMERANG
	const BOOMBURST
	const BOUNCE
	const BOUNCYBUBBLE
	const BRANCH_POKE
	const BRAVE_BIRD
	const BREAKNGSWIPE
	const BRICK_BREAK
	const BRINE
	const BRUTAL_SWING
	const BUBBLE
	const BUBBLE_BEAM
	const BUG_BITE
	const BUG_BUZZ
	const BULK_UP
	const BULLDOZE
	const BULLET_PUNCH
	const BULLET_SEED
	const BRNINGJEALSY
	const BUZZY_BUZZ
	const CALM_MIND
	const CAPTIVATE
	const CHARGE
	const CHARGE_BEAM
	const CHARM
	const CHATTER
	const CHIP_AWAY
	const CHLOROBLAST
	const CIRCLE_THROW
	const CLAMP
	const CLEAR_SMOG
	const CLOSE_COMBAT
	const COIL
	const COMET_PUNCH
	const CONFIDE
	const CONFUSE_RAY
	const CONFUSION
	const CONSTRICT
	const CONVERSION
	const CONVERSION2
	const COPYCAT
	const CORROSIVEGAS
	const COSMIC_POWER
	const COUNTER
	const COVET
	const CRABHAMMER
	const CROSS_CHOP
	const CROSS_POISON
	const CRUNCH
	const CRUSH_CLAW
	const CURSE
	const CUT
	const DARK_PULSE
	const DRKESTLARIAT
	const DAZZLNGGLEAM
	const DEFENSE_CURL
	const DEFOG
	const DESTINY_BOND
	const DETECT
	const DIG
	const DIRE_CLAW
	const DISABLE
	const DISARM_VOICE
	const DISCHARGE
	const DIVE
	const DIZZY_PUNCH
	const DOUBLE_HIT
	const DOUBLE_KICK
	const DOUBLE_SLAP
	const DOUBLE_TEAM
	const DOUBLE_EDGE
	const DRACO_METEOR
	const DRAGONBREATH
	const DRAGON_CLAW
	const DRAGON_DANCE
	const DRAGONHAMMER
	const DRAGON_PULSE
	const DRAGON_RAGE
	const DRAGON_RUSH
	const DRAGON_TAIL
	const DRAIN_PUNCH
	const DRAININGKISS
	const DREAM_EATER
	const DRILL_PECK
	const DRILL_RUN
	const DUAL_CHOP
	const DUALWINGBEAT
	const DYNAMICPUNCH
	const EARTH_POWER
	const EARTHQUAKE
	const ECHOED_VOICE
	const EERIEIMPULSE
	const EERIE_SPELL
	const EGG_BOMB
	const ELECTRO_BALL
	const ELECTROWEB
	const EMBARGO
	const EMBER
	const ENCORE
	const ENDEAVOR
	const ENDURE
	const ENERGY_BALL
	const ERUPTION
	const ESPER_WING
	const EXPAND_FORCE
	const EXPLOSION
	const EXTRASENSORY
	const EXTREMESPEED
	const FACADE
	const FAIRY_WIND
	const FAKE_OUT
	const FAKE_TEARS
	const FALSE_SWIPE
	const FEINT_ATTACK
	const FIERY_WRATH
	const FIRE_BLAST
	const FIRE_FANG
	const FIRE_PLEDGE
	const FIRE_PUNCH
	const FIRE_SPIN
	const FRSTIMPRESON
	const FISSURE
	const FLAIL
	const FLAME_BURST
	const FLAME_CHARGE
	const FLAME_WHEEL
	const FLAMETHROWER
	const FLARE_BLITZ
	const FLASH
	const FLASH_CANNON
	const FLATTER
	const FLOATY_FALL
	const FLY
	const FOCUS_BLAST
	const FOCUS_ENERGY
	const FOCUS_PUNCH
	const FORESIGHT
	const FOUL_PLAY
	const FREEZE_DRY
	const FREZINGGLARE
	const FREEZY_FROST
	const FRENZY_PLANT
	const FROST_BREATH
	const FRUSTRATION
	const FURY_ATTACK
	const FURY_CUTTER
	const FURY_SWIPES
	const FUTURE_SIGHT
	const GIGA_DRAIN
	const GIGA_IMPACT
	const GLARE
	const GLITZY_GLOW
	const GRASS_KNOT
	const GRASS_PLEDGE
	const GRASSWHISTLE
	const GROWL
	const GROWTH
	const GUILLOTINE
	const GUNK_SHOT
	const GUST
	const GYRO_BALL
	const HAIL
	const HAMMER_ARM
	const HARDEN
	const HAZE
	const HEAD_SMASH
	const HEADBUTT
	const HEADLONGRUSH
	const HEAL_BELL
	const HEART_STAMP
	const HEAT_WAVE
	const HEAVY_SLAM
	const HEX
	const HIDDEN_POWER
	const HIGHHORSPWER
	const HIGHJUMPKICK
	const HONE_CLAWS
	const HORN_ATTACK
	const HORN_DRILL
	const HOWL
	const HURRICANE
	const HYDRO_CANNON
	const HYDRO_PUMP
	const HYPER_BEAM
	const HYPER_FANG
	const HYPER_VOICE
	const HYPNOSIS
	const ICE_BALL
	const ICE_BEAM
	const ICE_FANG
	const ICE_PUNCH
	const ICE_SHARD
	const ICICLE_CRASH
	const ICICLE_SPEAR
	const ICY_WIND
	const INCINERATE
	const INFRNLPARADE
	const INFERNO
	const INFESTATION
	const IRON_DEFENSE
	const IRON_HEAD
	const IRON_TAIL
	const JUMP_KICK
	const KARATE_CHOP
	const KINESIS
	const KNOCK_OFF
	const LASER_FOCUS
	const LASH_OUT
	const LAVA_PLUME
	const LEAF_BLADE
	const LEAF_STORM
	const LEAF_TORNADO
	const LEAFAGE
	const LEECH_LIFE
	const LEECH_SEED
	const LEER
	const LICK
	const LIGHT_SCREEN
	const LIQUIDATION
	const LOCK_ON
	const LOVELY_KISS
	const LOW_KICK
	const LOW_SWEEP
	const LUCKY_CHANT
	const LUNGE
	const MACH_PUNCH
	const MAGICAL_LEAF
	const MAGNET_BOMB
	const MAGNITUDE
	const ME_FIRST
	const MEAN_LOOK
	const MEDITATE
	const MEGA_DRAIN
	const MEGA_KICK
	const MEGA_PUNCH
	const MEGAHORN
	const METAL_BURST
	const METAL_CLAW
	const METAL_SOUND
	const METEORASSULT
	const METEOR_BEAM
	const METEOR_MASH
	const METRONOME
	const MILK_DRINK
	const MIMIC
	const MIND_READER
	const MINIMIZE
	const MIRROR_COAT
	const MIRROR_MOVE
	const MIRROR_SHOT
	const MIST
	const MISTYEXPLSON
	const MOONBLAST
	const MOONLIGHT
	const MORNING_SUN
	const MUD_BOMB
	const MUD_SHOT
	const MUD_SLAP
	const MUDDY_WATER
	const MYSTICALFIRE
	const NASTY_PLOT
	const NIGHT_SHADE
	const NIGHT_SLASH
	const NIGHTMARE
	const NUZZLE
	const OCTAZOOKA
	const OMINOUS_WIND
	const OUTRAGE
	const OVERHEAT
	const PAIN_SPLIT
	const PAY_DAY
	const PAYBACK
	const PECK
	const PERISH_SONG
	const PETALBLIZARD
	const PETAL_DANCE
	const PHANTOMFORCE
	const PIKA_PAPOW
	const PIN_MISSILE
	const PLAY_NICE
	const PLAY_ROUGH
	const POISON_FANG
	const POISON_GAS
	const POISON_JAB
	const POISONPOWDER
	const POISON_STING
	const POLLEN_PUFF
	const POUND
	const POWDER_SNOW
	const POWER_GEM
	const POWER_WHIP
	const POWERUPPUNCH
	const PRESENT
	const PROTECT
	const PSYBEAM
	const PSYCH_UP
	const PSYCHIC_M
	const PSYCHICFANGS
	const PSYCHO_BOOST
	const PSYCHO_CUT
	const PSYSHELDBASH
	const PSYWAVE
	const PURSUIT
	const QUICK_ATTACK
	const QUIVER_DANCE
	const RAGE
	const RAGING_FURY
	const RAIN_DANCE
	const RAPID_SPIN
	const RAZOR_LEAF
	const RAZOR_SHELL
	const RAZOR_WIND
	const RECOVER
	const REFLECT
	const REST
	const RETURN
	const REVENGE
	const REVERSAL
	const RISNGVOLTAGE
	const ROAR
	const ROCK_BLAST
	const ROCK_CLIMB
	const ROCK_POLISH
	const ROCK_SLIDE
	const ROCK_SMASH
	const ROCK_THROW
	const ROCK_TOMB
	const ROCK_WRECKER
	const ROLLING_KICK
	const ROLLOUT
	const ROOST
	const ROUND_M
	const SACRED_FIRE
	const SAFEGUARD
	const SAND_ATTACK
	const SAND_TOMB
	const SANDSTORM
	const SAPPY_SEED
	const SCALD
	const SCALE_SHOT
	const SCARY_FACE
	const SCORCHNGSAND
	const SCRATCH
	const SCREECH
	const SEED_BOMB
	const SEISMIC_TOSS
	const SELFDESTRUCT
	const SHADOW_BALL
	const SHADOW_BONE
	const SHADOW_CLAW
	const SHADOW_PUNCH
	const SHADOW_SNEAK
	const SHARPEN
	const SHEER_COLD
	const SHELLSIDEARM
	const SHELL_SMASH
	const SHOCK_WAVE
	const SIGNAL_BEAM
	const SILVER_WIND
	const SING
	const SIZZLY_SLIDE
	const SKETCH
	const SKITTERSMACK
	const SKULL_BASH
	const SKY_ATTACK
	const SKY_DROP
	const SKY_UPPERCUT
	const SLACK_OFF
	const SLAM
	const SLASH
	const SLEEP_POWDER
	const SLEEP_TALK
	const SLUDGE
	const SLUDGE_BOMB
	const SLUDGE_WAVE
	const SMACK_DOWN
	const SMART_STRIKE
	const SMOG
	const SMOKESCREEN
	const SNARL
	const SNORE
	const SOFT_BOILED
	const SOLAR_BEAM
	const SOLAR_BLADE
	const SONIC_BOOM
	const SPARK
	const SPARKLYSWIRL
	const SPIDER_WEB
	const SPIKE_CANNON
	const SPIKES
	const SPITE
	const SPLASH
	const SPLISHYSPLSH
	const SPORE
	const STEEL_WING
	const STOMP
	const STMPNGTANTRM
	const STONE_AXE
	const STONE_EDGE
	const STORM_THROW
	const STRANGESTEAM
	const STRENGTH
	const STRING_SHOT
	const STRUGGLE
	const STRUGGLE_BUG
	const STUN_SPORE
	const SUBMISSION
	const SUBSTITUTE
	const SUNNY_DAY
	const SUPER_FANG
	const SUPERPOWER
	const SUPERSONIC
	const SURF
	const SWAGGER
	const SWEET_KISS
	const SWEET_SCENT
	const SWIFT
	const SWORDS_DANCE
	const SYNTHESIS
	const TACKLE
	const TAIL_SLAP
	const TAIL_WHIP
	const TAKE_DOWN
	const TEARFUL_LOOK
	const TEETER_DANCE
	const TELEPORT
	const THIEF
	const THRASH
	const THROAT_CHOP
	const THUNDER
	const THUNDER_FANG
	const THUNDERPUNCH
	const THUNDERSHOCK
	const THUNDER_WAVE
	const THUNDERBOLT
	const THUNDRUSKICK
	const TICKLE
	const TOXIC
	const TOXIC_THREAD
	const TRANSFORM
	const TRI_ATTACK
	const TRIPLE_AXEL
	const TRIPLE_KICK
	const TWINEEDLE
	const TWISTER
	const UPROAR
	const VACUUM_WAVE
	const VEEVEEVOLLEY
	const VENOSHOCK
	const VINE_WHIP
	const VISE_GRIP
	const VITAL_THROW
	const VOLT_TACKLE
	const WATER_GUN
	const WATER_PLEDGE
	const WATER_PULSE
	const WATERFALL
	const WHIRLPOOL
	const WHIRLWIND
	const WILD_CHARGE
	const WILL_O_WISP
	const WING_ATTACK
	const WISH
	const WITHDRAW
	const WOOD_HAMMER
	const WORK_UP
	const WRAP
	const X_SCISSOR
	const YAWN
	const ZAP_CANNON
	const ZEN_HEADBUTT
	const ZIPPY_ZAP
NUM_ATTACKS EQU const_value + -1

; Battle animations use the same constants as the moves up to this point
	const ANIM_SWEET_SCENT_2
	const ANIM_THROW_POKE_BALL
	const ANIM_SEND_OUT_MON
	const ANIM_RETURN_MON
	const ANIM_CONFUSED
	const ANIM_SLP
	const ANIM_BRN
	const ANIM_PSN
	const ANIM_SAP
	const ANIM_FRZ
	const ANIM_PAR
	const ANIM_IN_LOVE
	const ANIM_IN_SANDSTORM
	const ANIM_IN_HAIL
	const ANIM_IN_NIGHTMARE
	const ANIM_IN_WHIRLPOOL
; battle anims
	const ANIM_MISS
	const ANIM_ENEMY_DAMAGE
	const ANIM_ENEMY_STAT_DOWN
	const ANIM_PLAYER_STAT_DOWN
	const ANIM_PLAYER_DAMAGE
	const ANIM_WOBBLE
	const ANIM_SHAKE
	const ANIM_HIT_CONFUSION

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
